name: CI - E2E

# Run on direct pushes/PRs to main OR when the Unit workflow completes successfully.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: ["CI - Unit"]
    types:
      - completed

jobs:
  e2e:
    name: Playwright E2E
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies + Playwright
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest playwright

      - name: Install Playwright browsers
        run: |
          python -m playwright install

      - name: Start web app with gunicorn
        env:
          FLASK_SECRET: ci-secret
        run: |
          nohup gunicorn -b 127.0.0.1:5000 inventory.web:app > app.log 2>&1 &
          # wait for server to respond
          for i in {1..30}; do
            if curl -sSf http://127.0.0.1:5000/ >/dev/null 2>&1; then
              echo "server ready"
              break
            fi
            sleep 1
          done

      - name: Ensure reports dir
        run: |
          mkdir -p reports screenshots || true

      - name: Run Playwright E2E tests
        run: |
          pytest tests/e2e/test_toasts_playwright.py -q --junitxml=reports/e2e-results.xml

      - name: Compress app.log (if present)
        if: always()
        run: |
          if [ -f app.log ]; then
            gzip -c app.log > app.log.gz || true
            echo "Compressed app.log to app.log.gz"
          else
            echo "app.log not found"
          fi

      - name: Upload compressed app.log (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-app-log-gz
          path: app.log.gz

      - name: Upload E2E junit report (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-junit-report
          path: reports/e2e-results.xml

      - name: Upload Playwright screenshots (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-playwright-screenshots
          path: reports/screenshots

      - name: Archive screenshots and videos (if present)
        if: always()
        run: |
          set -e
          cd reports || exit 0
          if [ -d screenshots ]; then
            tar -czf screenshots.tar.gz screenshots || true
            echo "Archived screenshots"
          fi
          if [ -d videos ]; then
            tar -czf videos.tar.gz videos || true
            echo "Archived videos"
          fi
          cd -

      - name: Upload archived screenshots (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-screenshots-archive
          path: reports/screenshots.tar.gz

      - name: Upload archived videos (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-videos-archive
          path: reports/videos.tar.gz

      - name: Upload traces (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-traces
          path: reports/*.zip
